name: Cleanup Failed Workflow Runs
on:
  workflow_dispatch:
  jobs:
    cleanup:
        runs-on: ubuntu-latest
            steps:
                  - name: Delete
                          uses: dmvict/clean-workflow-runs@v1
                                  with:
                                            token: ${{ github.token }}
                                                      run_conclusions: failure
                                                                save_period: "02:00:00"
                                                                
